### update request to example server
 PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174012
Content-Type: application/json

{
  "name":"Aqrab",
  "address":"Aligarh",
  "dateOfBirth":"2005-12-10",
  "email": "abc1@mail.com"
}

###